dist: trusty

# configuration for build badge
language: scala

# configurations for codecov badge
scala:
  - 2.12.12

jdk:
  - oraclejdk8

script:
  - sbt test

after_success:
  - bash <(curl -s https://codecov.io/bash)
