version: 2.1
jobs:
  build:
    working_directory: ~/json
    docker:
      - image: openjdk:8
    environment:
      TZ: Asia/Tokyo
      JVM_OPTS: -Xms2G -Xmx2G -Xss2M -XX:ReservedCodeCacheSize=256m
    steps:
      - run:
          name: Get sbt binary
          command: |
            apt update && apt install -y curl
            echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
            echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | sudo tee /etc/apt/sources.list.d/sbt_old.list
            curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo apt-key add
            apt-get update
            apt-get install -y sbt
            apt-get clean && apt-get autoclean
      - checkout
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: sbt-cache
      - run:
          name: clean
          command: cat /dev/null | sbt clean
      - run:
          name: compile
          command: cat /dev/null | sbt test:compile
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
      - run:
          name: test json.AvatarValidationSpec
          command: cat /dev/null | sbt "testOnly json.validation.village.AvatarValidationSpec"
      - run:
          name: test json.BaseValidationSpec
          command: cat /dev/null | sbt "testOnly json.validation.village.BaseValidationSpec"
      - run:
          name: test json.CharacterValidationSpec
          command: cat /dev/null | sbt "testOnly json.validation.village.CharacterValidationSpec"
      - run:
          name: test json.RoleValidationSpec
          command: cat /dev/null | sbt "testOnly json.validation.village.RoleValidationSpec"
      - run:
          name: test json.AuthUnitTestSuite
          command: cat /dev/null | sbt "testOnly json.engine.auth.AuthUnitTestSuite"
      - run:
          name: test json.AuthProcessingEngineSuite
          command: cat /dev/null | sbt "testOnly json.engine.auth.AuthProcessingEngineSuite"
      - run:
          name: test json.LobbyUnitTestSuite
          command: cat /dev/null | sbt "testOnly json.engine.lobby.LobbyUnitTestSuite"
      - run:
          name: test json.LobbyProcessingEngineSuite
          command: cat /dev/null | sbt "testOnly json.engine.lobby.LobbyProcessingEngineSuite"
      - run:
          name: test json.VillageUnitTestSuite
          command: cat /dev/null | sbt "testOnly json.engine.village.VillageUnitTestSuite"
      - run:
          name: test json.VillageProcessingEngineSuite
          command: cat /dev/null | sbt "testOnly json.engine.village.VillageProcessingEngineSuite"
      - run:
          name: test json.server2logger.VillageProcessingEngineSuite
          command: cat /dev/null | sbt "testOnly json.engine.village.server2logger.VillageProcessingEngineSuite"
      - run:
          name: test protocol.AuthProcessingEngineSuite
          command: cat /dev/null | sbt "testOnly protocol.engine.auth.AuthProcessingEngineSuite"
      - run:
          name: test protocol.LobbyProcessingEngineSuite
          command: cat /dev/null | sbt "testOnly protocol.engine.lobby.LobbyProcessingEngineSuite"
      - run:
          name: test protocol.VillageProcessingEngineSuite
          command: cat /dev/null | sbt "testOnly protocol.engine.village.VillageProcessingEngineSuite"
      - run:
          name: test protocol.server2logger.VillageProcessingEngineSuite
          command: cat /dev/null | sbt "testOnly protocol.engine.village.server2logger.VillageProcessingEngineSuite"
      - run:
          name: test async.protocol.AuthProcessingEngineSuite
          command: cat /dev/null | sbt "testOnly protocol.engine.async.auth.AuthProcessingEngineSuite"
      - run:
          name: test async.protocol.LobbyProcessingEngineSuite
          command: cat /dev/null | sbt "testOnly protocol.engine.async.lobby.LobbyProcessingEngineSuite"
      - run:
          name: test async.protocol.VillageProcessingEngineSuite
          command: cat /dev/null | sbt "testOnly protocol.engine.async.village.VillageProcessingEngineSuite"
      - run:
          name: test async.protocol.server2logger.VillageProcessingEngineSuite
          command: cat /dev/null | sbt "testOnly protocol.engine.async.village.server2logger.VillageProcessingEngineSuite"
      - run:
          name: test protocol.engine.auth.JAuthProcessingEngineSuite
          command: cat /dev/null | sbt "testOnly protocol.engine.auth.JAuthProcessingEngineSuite"
      - run:
          name: test protocol.engine.lobby.JLobbyProcessingEngineSuite
          command: cat /dev/null | sbt "testOnly protocol.engine.lobby.JLobbyProcessingEngineSuite"
      - run:
          name: test protocol.engine.village.JVillageProcessingEngineSuite
          command: cat /dev/null | sbt "testOnly protocol.engine.village.JVillageProcessingEngineSuite"