name: Scala CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run tests
        run: sbt Test/test
      - name: Migrate scalac options
        run: sbt "migrate-scalacOptions json"
      - name: Migrate libraries
        run: sbt "migrate-libs json"
